language: ruby
rvm:
  - 2.3.0
script:
  - bin/rails db:migrate RAILS_ENV=test
  - bundle exec rake
  - bundle exec rubocop
branches:
  only:
    - master
    - develop

addons:
  code_climate:
    repo_token: 9822ef8707167cba8d26129649ead153d04940535e7396c3beae417505015f00 
